name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m venv .midas-venv
        source .midas-venv/bin/activate
        pip install -r requirements.txt
    - name: Lint code
      run: |
        source .midas-venv/bin/activate
        flake8 .
    - name: DBT compile
      run: |
        source .midas-venv/bin/activate
        dbt compile --profiles-dir ./dbt
    - name: Run basic tests
      run: |
        source .midas-venv/bin/activate
        pytest tests/
    - name: Airflow DAG Validation
      run: |
        source .midas-venv/bin/activate
        python -m airflow dags list
        python -m airflow dags test ingestion_dag midas_test_run
    - name: Airflow Start API Server
      run: |
        source .midas-venv/bin/activate
        airflow api-server -p 8080 &
        sleep 10
        curl -f http://localhost:8080/